# Setup
title:        Niklas Inde
tagline:      Everything i may or may not need in the future
baseurl:      niklasinde.github.io
paginate:     1

# About/contact
author:
  name:       Niklas Inde
  url:        https://niklasinde.github.io

# Gems
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

#Others
markdown: kramdown
kramdown:
  math_engine: mathjax
